services:
  front:
    build: ./front
    volumes:
      - type: bind
        source: ./front/src
        target: /usr/local/app/src
    ports: ["4200:4200"]
    networks:
      - app-network

  back:
    build: ./back
    volumes:
      - type: bind
        source: ./back/src
        target: /usr/local/app/src
    ports: ["8000:8000"]
    environment:
      username: "test"
      password: "test"
      CONFLUENCE_BASE_URL: "test"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
