services:
  front:
    build: ./front
    volumes:
      - type: bind
        source: ./front/src
        target: /usr/local/app/src
    ports: ["4200:4200"]

  back:
    build: ./back
    volumes:
      - type: bind
        source: ./back/src
        target: /usr/local/app/src
    ports: ["80:80"]
    environment:
      username: "test"
      password: "test"
      CONFLUENCE_BASE_URL: "test"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
